createCart:
    path: /api/carts
    controller: ShoppingCartAPI\Controller\CreateCartController
    methods: [POST]

getCart:
    path: /api/carts/{id}
    controller: ShoppingCartAPI\Controller\GetCartController
    methods: [GET]

addProductToCart:
    path: /api/carts/{id}
    controller: ShoppingCartAPI\Controller\AddProductToCartController
    methods: [POST]

deleteCart:
    path: /api/carts/{id}
    controller: ShoppingCartAPI\Controller\DeleteCartController
    methods: [DELETE]
