createCart:
    path: /api/carts
    controller: ShoppingCartAPI\Controller\CreateCartController
    methods: [POST]

getCart:
    path: /api/carts/{id}
    controller: ShoppingCartAPI\Controller\GetCartController
    methods: [GET]
