
version: '3.8'

services:
  php_container:
    build:
      context: etc/infrastructure/php
      dockerfile: Dockerfile
    container_name: php_container
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 9001:9000

  nginx_container:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 8000:80
    volumes:
      - ./etc/infrastructure/nginx/conf.d:/etc/nginx/conf.d
      - ./apps/ShoppingCartAPI/public/:/app/apps/ShoppingCartAPI/public
    depends_on:
      - php_container

  redis_container:
    image: redis
    ports:
      - ${REDIS_PORT}:6379
    expose:
      - 6379
    volumes:
      - ./var/redis:/data/redis

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    volumes:
      - ./var/redisinsight:/db
    depends_on:
      - redis_container
