# Create an empty cart
POST http://localhost:8000/api/carts

{
}


###
# Get a cart
GET http://localhost:8000/api/carts/{{cartId}}


###
# Add a product to a cart
POST http://localhost:8000/api/carts/{{cartId}}

{
  "productId": "{{productId}}",
  "productQuantity": 2
}


###
# Delete a cart
DELETE http://localhost:8000/api/carts/{{cartId}}


###
# Change cart line quantity
PATCH http://localhost:8000/api/carts/{{cartId}}/items/{{productId}}

{
  "productQuantity": 3
}
