# Create an empty cart
POST {{url}}/api/carts

{
  "userId": "{{userId}}"
}

###
# Get a cart
GET {{url}}/api/carts/{{cartId}}

###
# Add a product to a cart
POST {{url}}/api/carts/{{cartId}}

{
  "productId": "{{productId}}",
  "productQuantity": 2
}

###
# Remove a product from cart
DELETE {{url}}/api/carts/{{cartId}}/items/{{productId}}

{
}

###
# Change cart line quantity
PATCH {{url}}/api/carts/{{cartId}}/items/{{productId}}

{
  "productQuantity": 3
}

###
# Delete a cart
DELETE {{url}}/api/carts/{{cartId}}

###
# Checkout cart
POST {{url}}/api/carts/{{cartId}}/checkout

{
}
